# tmux plugin manager; plugins themselves are installed by run_onchange_after_20-tmux-plugins.sh
[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm.git"
    refreshPeriod = "168h"
